clang -emit-llvm -S -g3 ./test/test00.c -o ./outfiles/test00.bc
clang -emit-llvm -S -g3 ./test/test01.c -o ./outfiles/test01.bc
clang -emit-llvm -S -g3 ./test/test02.c -o ./outfiles/test02.bc
clang -emit-llvm -S -g3 ./test/test03.c -o ./outfiles/test03.bc
clang -emit-llvm -S -g3 ./test/test04.c -o ./outfiles/test04.bc
clang -emit-llvm -S -g3 ./test/test05.c -o ./outfiles/test05.bc
clang -emit-llvm -S -g3 ./test/test06.c -o ./outfiles/test06.bc
clang -emit-llvm -S -g3 ./test/test07.c -o ./outfiles/test07.bc
clang -emit-llvm -S -g3 ./test/test08.c -o ./outfiles/test08.bc
clang -emit-llvm -S -g3 ./test/test09.c -o ./outfiles/test09.bc
clang -emit-llvm -S -g3 ./test/test10.c -o ./outfiles/test10.bc
clang -emit-llvm -S -g3 ./test/test11.c -o ./outfiles/test11.bc
clang -emit-llvm -S -g3 ./test/test12.c -o ./outfiles/test12.bc
clang -emit-llvm -S -g3 ./test/test13.c -o ./outfiles/test13.bc
clang -emit-llvm -S -g3 ./test/test14.c -o ./outfiles/test14.bc
clang -emit-llvm -S -g3 ./test/test15.c -o ./outfiles/test15.bc
clang -emit-llvm -S -g3 ./test/test16.c -o ./outfiles/test16.bc
clang -emit-llvm -S -g3 ./test/test17.c -o ./outfiles/test17.bc
clang -emit-llvm -S -g3 ./test/test18.c -o ./outfiles/test18.bc
clang -emit-llvm -S -g3 ./test/test19.c -o ./outfiles/test19.bc
clang -emit-llvm -S -g3 ./test/test20.c -o ./outfiles/test20.bc
clang -emit-llvm -S -g3 ./test/test21.c -o ./outfiles/test21.bc
clang -emit-llvm -S -g3 ./test/test22.c -o ./outfiles/test22.bc
clang -emit-llvm -S -g3 ./test/test23.c -o ./outfiles/test23.bc
clang -emit-llvm -S -g3 ./test/test24.c -o ./outfiles/test24.bc
clang -emit-llvm -S -g3 ./test/test25.c -o ./outfiles/test25.bc
clang -emit-llvm -S -g3 ./test/test26.c -o ./outfiles/test26.bc
clang -emit-llvm -S -g3 ./test/test27.c -o ./outfiles/test27.bc
clang -emit-llvm -S -g3 ./test/test28.c -o ./outfiles/test28.bc
clang -emit-llvm -S -g3 ./test/test29.c -o ./outfiles/test29.bc
clang -emit-llvm -S -g3 ./test/test30.c -o ./outfiles/test30.bc
clang -emit-llvm -S -g3 ./test/test31.c -o ./outfiles/test31.bc
clang -emit-llvm -S -g3 ./test/test32.c -o ./outfiles/test32.bc
clang -emit-llvm -S -g3 ./test/test33.c -o ./outfiles/test33.bc
clang -emit-llvm -S -g3 ./test/test34.c -o ./outfiles/test34.bc
